apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include ".helm.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include ".helm.fullname" . }}
    appRevision: {{ template ".helm.nameRevision" . }}
    release: {{ include ".helm.fullname" . }}
    releaseRevision: {{ .Release.Revision | quote }}
    {{- include ".helm.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include ".helm.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include ".helm.fullname" . }}
    namespace: {{ .Release.Namespace }}
