
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "commons.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "commons.labels" . | nindent 4 }}
rules:
- apiGroups: ["wyrihaximus.net"]
  resources: ["redis-databases"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["create", "patch", "get"]
