apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "commons.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "commons.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "commons.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "commons.fullname" . }}
    namespace: {{ .Release.Namespace }}
