apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include ".helm.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include ".helm.fullname" . }}
    appRevision: {{ template ".helm.nameRevision" . }}
    release: {{ include ".helm.fullname" . }}
    releaseRevision: {{ .Release.Revision | quote }}
    {{- include ".helm.labels" . | nindent 4 }}
