apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "commons.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "commons.fullname" . }}
    appRevision: {{ template "commons.nameRevision" . }}
    release: {{ include "commons.fullname" . }}
    releaseRevision: {{ .Release.Revision | quote }}
    {{- include "commons.labels" . | nindent 4 }}
