{{- if gt (.Values.replicas | int) 1 -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "commento.fullname" . }}-pdb
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ include "commento.fullname" . }}
      release: {{ include "commento.fullname" . }}
{{ end }}