{{- if .Values.cron.replaceOldestPodHourly -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "default-backend.fullname" . }}-recycle-cronjob
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "default-backend.fullname" . }}
    appRevision: {{ template "default-backend.nameRevision" . }}
    release: {{ include "default-backend.fullname" . }}
    releaseRevision: {{ .Release.Revision | quote }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "delete"]
{{ end }}
