{{- if .Values.cron.replaceOldestPodHourly -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "commons.fullname" . }}-recycle-cronjob
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "commons.labels" . | nindent 4 }}
{{ end }}
