{{- if .Values.cron.replaceOldestPodHourly -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "default-backend.fullname" . }}-recycle-cronjob
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "default-backend.fullname" . }}
    appRevision: {{ template "default-backend.nameRevision" . }}
    release: {{ include "default-backend.fullname" . }}
    releaseRevision: {{ .Release.Revision | quote }}
    {{- include "default-backend.labels" . | nindent 4 }}
{{ end }}
