{{- if .Values.cron.replaceOldestPodHourly -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "commons.fullname" . }}-recycle-cronjob
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "commons.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "commons.fullname" . }}-recycle-cronjob
subjects:
  - kind: ServiceAccount
    name: {{ include "commons.fullname" . }}-recycle-cronjob
    namespace: {{ .Release.Namespace }}
{{ end }}
