{{- if not (empty .Values.ingress.hosts) -}}
{{- $chartName := .Chart.Name -}}
{{- $fullName := include "commons.fullname" . -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "commons.labels" . | nindent 4 }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  tls:
    {{- range .Values.ingress.hosts }}
    - hosts:
        - {{ . }}
      secretName: tls-{{ . | replace "." "-" }}
    {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: default-backend
    {{- end }}
{{ end }}
