apiVersion: v1
kind: Service
metadata:
  name: {{ template "commons.fullname" . }}
  labels:
    {{- include "commons.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 6969
      targetPort: default-backend
      protocol: TCP
      name: default-backend
    - port: 9696
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app: {{ template "commons.name" . }}
    release: {{ .Release.Name }}
