{{- if .Values.cron.replaceOldestPodWeekly -}}
{{- include "cron-jobs.cronjob" (fromYaml (.Files.Get "values/cronjob.yaml" | replace "[[fullname]]" (include ".helm.fullname" .) | replace "[[app]]" (include ".helm.name" .) | replace "[[release]]" .Release.Name | replace "[[namespace]]" .Release.Namespace)) -}}
{{ end }}
