apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "commons.fullname" . }}
  labels:
    {{- include "commons.labels" . | nindent 4 }}
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "commons.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "7133"
      labels:
        app: {{ template "commons.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: {{ template "commons.name" . }}
        app.kubernetes.io/version: {{ .Chart.Version | quote }}
        appRevision: {{ template "commons.nameRevision" . }}
        chart: {{ template "commons.chart" . }}
        helm.sh/chart: {{ template "commons.chart" . }}
        release: {{ .Release.Name }}
        releaseRevision: {{ .Release.Revision | quote }}
        heritage: {{ .Release.Service }}
        {{- toYaml .Values.labels | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "redirect.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 7132
              protocol: TCP
            - name: http-metrics
              containerPort: 7133
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http-metrics
          readinessProbe:
            httpGet:
              path: /ping
              port: http-metrics
          startupProbe:
            failureThreshold: 33
            periodSeconds: 1
            httpGet:
              path: /ping
              port: http-metrics
          volumeMounts:
            - name: {{ include "commons.fullname" . }}-volume
              mountPath: /etc/redirect/
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: {{ include "commons.fullname" . }}-volume
          configMap:
            name: {{ include "commons.fullname" . }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: appRevision
                operator: In
                values:
                - {{ template "commons.nameRevision" . }}
            topologyKey: "kubernetes.io/hostname"
