apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include ".helm.fullname" . }}
  labels:
    app: {{ include ".helm.fullname" . }}
    release: {{ include ".helm.fullname" . }}
    {{- include ".helm.labels" . | nindent 4 }}
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include ".helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "7133"
      labels:
        app: {{ include ".helm.fullname" . }}
        release: {{ include ".helm.fullname" . }}
        {{- include ".helm.selectorLabels" . | nindent 8 }}
        {{- toYaml .Values.labels | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include ".helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 7132
              protocol: TCP
            - name: http-metrics
              containerPort: 7133
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http-metrics
          readinessProbe:
            httpGet:
              path: /ping
              port: http-metrics
          startupProbe:
            failureThreshold: 33
            periodSeconds: 1
            httpGet:
              path: /ping
              port: http-metrics
          volumeMounts:
            - name: {{ include ".helm.fullname" . }}-volume
              mountPath: /etc/redirect/
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: {{ include ".helm.fullname" . }}-volume
          configMap:
            name: {{ include ".helm.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
