{{- $fullName := include "commons.fullname" . -}}
{{- $hosts := concat (.Values.redirect.ingressHosts | mustDeepCopy) (.Values.redirect.hosts | mustDeepCopy | keys) -}}
{{- range $host := ($hosts | uniq) }}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-{{ $host  | replace "." "-" }}
  labels:
    {{- include "commons.labels" $ | nindent 4 }}
  {{- with $.Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
    {{ include "redirect.hostTLS" (dict "Host" $host) | nindent 4 }}
  rules:
    {{ include "redirect.hostRule" (dict "Host" $host "FullName" $fullName "SvcPort" 7132) | nindent 4 }}
{{- end }}
