{{- $fullName := include "commons.fullname" . -}}
{{- $hosts := .Values.redirect.hosts -}}
{{- $ingressHosts := .Values.redirect.ingressHosts -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "commons.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
  {{- if $hosts -}}
    {{- range $hostFrom, $hostTo := $hosts }}
      {{- $host := dict "Host" $hostFrom -}}
      {{ include "redirect.hostTLS" $host | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- if $ingressHosts -}}
    {{- range $host := $ingressHosts }}
      {{- if eq (hasKey $hosts $host) false -}}
        {{- $host := dict "Host" $host -}}
        {{ include "redirect.hostTLS" $host | nindent 4 }}
      {{- end }}
    {{- end }}
  {{- end }}
  rules:
  {{- if $hosts -}}
    {{- range $hostFrom, $hostTo := $hosts }}
      {{- $host := dict "Host" $hostFrom "FullName" $fullName "SvcPort" 7132 -}}
      {{ include "redirect.hostRule" $host | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- if $ingressHosts -}}
    {{- range $host := $ingressHosts }}
      {{- if eq (hasKey $hosts $host) false -}}
        {{- $host := dict "Host" $host "FullName" $fullName "SvcPort" 7132 -}}
        {{ include "redirect.hostRule" $host | nindent 4 }}
      {{- end }}
    {{- end }}
  {{- end }}
