{{- if gt (.Values.replicas | int) 1 -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include ".helm.fullname" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ include ".helm.fullname" . }}
      release: {{ include ".helm.fullname" . }}
{{ end }}