apiVersion: v1
kind: Service
metadata:
  name: {{ include ".helm.fullname" . }}
  labels:
    {{- include ".helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 7132
      targetPort: 7132
      protocol: TCP
      name: http
    - port: 7133
      targetPort: 7133
      protocol: TCP
      name: http-metrics
  selector:
    {{- include ".helm.selectorLabels" . | nindent 4 }}
