apiVersion: v1
kind: Service
metadata:
  name: {{ include "commons.fullname" . }}
  labels:
    {{- include "commons.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 7132
      targetPort: 7132
      protocol: TCP
      name: http
    - port: 7133
      targetPort: 7133
      protocol: TCP
      name: http-metrics
  selector:
    app.kubernetes.io/name: {{ include "commons.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
