apiVersion: v2
name: docker-hub-exporter
description: Docker Hub exporter
home: https://github.com/jessestuart/docker-hub-exporter
icon: https://helm.wyrihaximus.net/images/charts/docker-hub-exporter.png
type: application
version: 0.1.5
appVersion: d05df48
maintainers:
  - name: WyriHaximus
    email: helm@wyrihaximus.net
