image:
  repository: jessestuart/docker-hub-exporter
  tag: d05df48
  pullPolicy: IfNotPresent

organisations: YOUR_USER_OR_ORG

grafana:
  influxdb: false
  prometheus: false

resources:
  # Setting this pretty low since this is a low resource intensive application, increase when needed
  limits:
    cpu: 5m
    memory: 31Mi
  requests:
    cpu: 5m
    memory: 31Mi
