{{- if gt (.Values.replicas | int) 1 -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "commons.fullname" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "commons.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{ end }}
