apiVersion: v1
kind: Service
metadata:
  name: {{ include "commons.fullname" . }}
  labels:
    {{- include "commons.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9617
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "commons.selectorLabels" . | nindent 4 }}
