apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include ".helm.fullname" . }}
  labels:
    app: {{ include ".helm.fullname" . }}
    release: {{ include ".helm.fullname" . }}
    {{- include ".helm.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include ".helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9170"
      labels:
        app: {{ include ".helm.fullname" . }}
        release: {{ include ".helm.fullname" . }}
        {{- include ".helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: docker-hub-exporter
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: 9170
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 5
            httpGet:
              path: /
              port: metrics
          readinessProbe:
            initialDelaySeconds: 5
            httpGet:
              path: /
              port: metrics
          args:
            - -listen-address=:9170
            - -organisations={{ .Values.organisations }}
