apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "commons.fullname" . }}
  labels:
    {{- include "commons.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "commons.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9170"
      labels:
        {{- include "commons.labels" . | nindent 8 }}
    spec:
      containers:
        - name: docker-hub-exporter
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: 9170
              protocol: TCP
          livenessProbe:
            failureThreshold: 9
            periodSeconds: 20
            initialDelaySeconds: 20
            httpGet:
              path: /
              port: metrics
          readinessProbe:
            failureThreshold: 9
            periodSeconds: 20
            initialDelaySeconds: 20
            httpGet:
              path: /
              port: metrics
          startupProbe:
            failureThreshold: 33
            periodSeconds: 1
            httpGet:
              path: /
              port: metrics
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          args:
            - -listen-address=:9170
            - -organisations={{ .Values.organisations }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ template "commons.nameRevision" . }}
            topologyKey: "kubernetes.io/hostname"
