name: "helm-charts/test"

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Lint charts
        id: lint
        uses: helm/chart-testing-action@v1.1.0
        with:
          command: lint
          config: ct.yaml


  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0-alpha.3
        with:
          installLocalPathProvisioner: true
        # Only build a kind cluster if there are chart changes to test.

      - name: Prepare library charts
        run: |
          cp charts/cron-jobs/library-ci/*.yaml charts/cron-jobs/templates/
          cp charts/horizontal-pod-autoscalers/library-ci/*.yaml charts/horizontal-pod-autoscalers/templates/
          sed -i 's/library/application/g' charts/cron-jobs/Chart.yaml
          sed -i 's/library/application/g' charts/horizontal-pod-autoscalers/Chart.yaml

      - name: Test charts
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: install
