name: "helm-charts/test"

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch history
        run: git fetch --prune --unshallow
      - name: Lint charts
        id: lint
        uses: helm/chart-testing-action@v2.1.0
        with:
          command: lint
          config: ct.yaml

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
        with:
          installLocalPathProvisioner: true # Only build a kind cluster if there are chart changes to test.

      - name: Install postgresql
        uses: evryfs/helm-ephemeral-action@v0.1.15
        with:
          repo: https://charts.bitnami.com/bitnami
          chart: postgresql
          helm: 'helm' # optional, default value is 'helm'
          args: '--wait --timeout 13m' #optional, default value is '--wait --timeout 2m' in order to wait for the chart-install to stabilize into ready state
      - name: Get PG password
        id: postgresql_password
        run: |
          echo ::set-output name=password::$(echo "$(kubectl get secret --namespace default postgresql-helm-charts-${{ github.run_number }} -o jsonpath="{.data.postgresql-password}" | base64 --decode)")
      - name: Create postgresql URL
        id: postgresql
        run: |
          echo ::set-output name=url::$(echo "postgresql://postgres:${{ steps.postgresql_password.outputs.password }}@postgresql-helm-charts-${{ github.run_number }}.default/postgres")
      - name: Prepare library charts
        run: |
          cp charts/commons/library-ci/*.yaml charts/commons/templates/
          cp charts/cron-jobs/library-ci/*.yaml charts/cron-jobs/templates/
          cp charts/horizontal-pod-autoscalers/library-ci/*.yaml charts/horizontal-pod-autoscalers/templates/
          cp charts/pi-hole-exporter/library-ci/*.yaml charts/pi-hole-exporter/templates/
          sed -i '$ d' charts/commento/ci/postgresql-values.yaml
          echo -e "  manual: \"${{ steps.postgresql.outputs.url }}\"\r\n" >> charts/commento/ci/postgresql-values.yaml
          sed -i '$ d' charts/commentoplusplus/ci/postgresql-values.yaml
          echo -e "  manual: \"${{ steps.postgresql.outputs.url }}\"\r\n" >> charts/commentoplusplus/ci/postgresql-values.yaml
          sed -i 's/library/application/g' charts/commons/Chart.yaml
          sed -i 's/library/application/g' charts/cron-jobs/Chart.yaml
          sed -i 's/library/application/g' charts/horizontal-pod-autoscalers/Chart.yaml
          rm -Rf charts/commento
          rm -Rf charts/commentoplusplus
      - name: Test charts
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: install
